/*

 MAINCHAR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define maincharBank 0

/* Super Gameboy palette 0 */
#define maincharSGBPal0c0 9298
#define maincharSGBPal0c1 31950
#define maincharSGBPal0c2 17421
#define maincharSGBPal0c3 761

/* Super Gameboy palette 1 */
#define maincharSGBPal1c0 6076
#define maincharSGBPal1c1 8935
#define maincharSGBPal1c2 6596
#define maincharSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define maincharSGBPal2c0 6076
#define maincharSGBPal2c1 8935
#define maincharSGBPal2c2 6596
#define maincharSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define maincharSGBPal3c0 6076
#define maincharSGBPal3c1 8935
#define maincharSGBPal3c2 6596
#define maincharSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define maincharCGBPal0c0 0
#define maincharCGBPal0c1 16912
#define maincharCGBPal0c2 25368
#define maincharCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define maincharCGBPal1c0 6076
#define maincharCGBPal1c1 8935
#define maincharCGBPal1c2 6596
#define maincharCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define maincharCGBPal2c0 6076
#define maincharCGBPal2c1 8935
#define maincharCGBPal2c2 6596
#define maincharCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define maincharCGBPal3c0 6076
#define maincharCGBPal3c1 8935
#define maincharCGBPal3c2 6596
#define maincharCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define maincharCGBPal4c0 6076
#define maincharCGBPal4c1 8935
#define maincharCGBPal4c2 6596
#define maincharCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define maincharCGBPal5c0 6076
#define maincharCGBPal5c1 8935
#define maincharCGBPal5c2 6596
#define maincharCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define maincharCGBPal6c0 6076
#define maincharCGBPal6c1 8935
#define maincharCGBPal6c2 6596
#define maincharCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define maincharCGBPal7c0 6076
#define maincharCGBPal7c1 8935
#define maincharCGBPal7c2 6596
#define maincharCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char mainchar[];

/* End of MAINCHAR.H */
